### ISSUE TITLE
Make the location folder optional

### ISSUE THREAD

**Issue by danwhite85** [jmathai/elodie#136]
I think it'd be nice if the location folder was optional. It could still default to true.

**Comment by jmathai** [comment]
@danwhite85 Do you mean the destination folder should be optional? If so where were you thinking the photos/videos should be sorted into?

**Comment by danwhite85** [comment]
No, I mean the geolocation folder. If it were set to false the files would just sorted into their month folder.

**Comment by jmathai** [comment]
@danwhite85 instead of adding a flag I added a check to see if the MapQuest key was not found then it would skip the lookup. This is really a performance fix because prior to this fix if there wasn't a key it would do the lookup and fail. Now it skips the lookup.

Should be a decent performance gain since you're not having to do a HTTP call for every file.

Thanks for the suggestion.

**Comment by danwhite85** [comment]
Awesome! Thx
