### ISSUE TITLE
Folder respect when no data or gps are found

### ISSUE THREAD

**Issue by patricksan** [jmathai/elodie#16]
I already have this kind of organisation in my photos: 
<img width="407" alt="screen shot 2015-12-03 at 00 00 14" src="https://cloud.githubusercontent.com/assets/81615/11546981/e1879fd0-9950-11e5-90a7-752aad9ca1ce.png">

if I import, probably I will loose all information as years ago we didn't embedded dates/gps on photos.

How could we solve this problem?

**Comment by jmathai** [comment]
The obvious solution would be to use the existing folder name as an album name. That would keep that information in the organized folder structure. How we do that is good question but I think the mechanism to do it is already there.

Very good suggestion.

**Comment by patricksan** [comment]
I would even create inside a folder like “NEED_ATTENTION”, “TO BE PROCESS”, “Unkown Data”. So I know I could drop the images to Elodie when I have time and fix it by hand: date (at least month/year) and gps.

**Comment by patricksan** [comment]
--preserve-my-folders

maybe that would be a nice parameter. Just used to import and when no date or geo information is found.

if the re is a name, we may use as part of the new struct.

**Comment by jmathai** [comment]
It's important that the program doesn't simply place a file into a folder. It needs to also store that back into the photo so if it's reprocessed that it will be processed correctly. That's why I think the "folder" needs to map to an "album". I think something along the lines of a parameter `--album-from-folder` which, if present, will add the folder as the album.

**Comment by patricksan** [comment]
Good idea!

**Comment by jmathai** [comment]
Merged in gh-20
