### ISSUE TITLE
returned language from mapquest

### ISSUE THREAD

**Issue by gokaytuna** [jmathai/elodie#236]
Hey guys, everything is working great sofar, thanks a lot for elodie . I have the following challenge though. When the request is made to mapquest, the result comes back for russian cities in russian or for arabic cities and countries in arabic.
i saw accepted_language in constants.py but apparently it is not used anywhere, do you know how we can retrieve only the english names for the countries and cities as well as the states.
Thanks in advance
Best, Goekay

**Comment by jmathai** [comment]
@gokaytuna can you try to update [this line](https://github.com/jmathai/elodie/blob/master/elodie/geolocation.py#L175) to the following?
```
        params = {'format': 'json', 'accept-language': constants.accept_language, 'key': key}
```

**Comment by jmathai** [comment]
*ping* @gokaytuna

**Comment by ethack** [comment]
I had the exact same issue and now I feel silly.  I spent a couple hours tracing through code and reading MapQuest/OpenStreetMap documentation to come up with that solution :(  And I didn't even realize constants.py had the language as a config option until I went to create an issue and saw this was already here.

Long story short, your change works for me.

Before: (using %country/%city)
```
Hrvatska/Split
Österreich/Wein
```

After:
```
Croatia/Split
Austria/Vienna
```

**Comment by jmathai** [comment]
Thanks for confirming that the fix works. In order to fix this properly I'd like to make it so there's a consistent way to override configuration values.

Problem is that some of the configuration values are in `config.ini` and others are in `constants.py`. I'd like to move to a model where there's a `config.ini` that is checked into the repository and you can add your own config-override.ini if you'd like.

#247 was my original approach by making `constants.py` overridable by making a `constants_override.py` file. But that litters configuration values across various files. I'll keep #247 open for now but will update it to follow the preferred model of having all configs in the `ini` files and removing constants.py altogether.

**Comment by ethack** [comment]
Combining `constants.py` and `config.ini` sounds like a good idea to me.

I also just noticed a small typo in the fix I tested above.  Maybe I corrected it without realizing it when I tested it.  It should be `constants.accepted_language` rather than `constants.accept_language` to match the variable name in `constants.py`.

```
 params = {'format': 'json', 'accept-language': constants.accepted_language, 'key': key}
```

**Comment by DZamataev** [comment]
Ok guys, after this PR https://github.com/jmathai/elodie/pull/290 you can easily add ```prefer_english_names=True``` to the ```[MapQuest]``` section of the config. Then MapQuest will do it's best to give you English names. That does not always work but mostly it does.
@jmathai may close the issue.
