### ISSUE TITLE
Hazel script

### ISSUE THREAD

**Issue by MacAdda** [jmathai/elodie#24]
I am new with Hazel script stuff. Do you mind to describe the rule you made in Hazel to notify Elodie to do this:
"to set up a Hazel rule to notify me when photos arrive in `~/Downloads` so I can import them."

Thanks

**Comment by jmathai** [comment]
Leaving this open to include it in the documentation.

Here's a screenshot of one of my rules. It watches `~/Downloads` for photos, waits 1 minute, then processes it. The 1 minute wait is so I have time to move them somewhere else since other apps save to `~/Downloads`.

This is the script which executes. Yours may vary depending on where your checked out the source. I checked out to `~/.elodie/elodie`.

```
/Users/jmathai/.elodie/elodie/elodie.py import --file="$1"  --destination="/Users/jmathai/Google Drive/Google Photos" >> /Users/jmathai/.elodie/output.log
```

<img width="670" alt="system preferences - hazel - screen shot dec 9 2015 10 00 25 am" src="https://cloud.githubusercontent.com/assets/6384/11693864/0f0e298c-9e5c-11e5-9a20-702ce10583d8.png">

**Comment by jmathai** [comment]
Exporting the Hazel script looks to be binary and not text so I can't really post it in the docs. Closing since the screenshot and embedded code should be sufficient.
