### ISSUE TITLE
Moving pictures with no DateTimeOriginal to folder

### ISSUE THREAD

**Issue by thomaspriv** [jmathai/elodie#364]
Hi There,

I set up elodie to go over some test files and so far everything is working just fine.

It seems that pictures which have been received through Whatsapp are also transformed by elodie but with the wrong filename.
Elodie is using FileModifyDate instead of ModifyDate (I assume) to create the filename. (as Whatsapp strippes all EXIF data)

> FileModifyDate -> tags stored in the filesystem
> ModifyDate -> tags stored in the metadata of the file.

example EXIF data of a Whatsapp picture
```
thomas@ubuntu:~/elodie$ exiftool -time:all -G0:1 -s /home/thomas/pictures/IMG-20200307-WA0001.jpg
[File:System]   FileModifyDate                  : 2020:04:08 11:09:23+00:00
[File:System]   FileAccessDate                  : 2020:04:08 12:06:58+00:00
[File:System]   FileInodeChangeDate             : 2020:04:08 12:02:03+00:00
```

command used with elodie
`./elodie.py import --debug --destination="/home/thomas/output" /home/thomas/pictures`
resulting name of the file after running elodie
`2020-04-08_11:09:23-img-20200307-wa0001.jpg`  

I can run the following command to populate the EXIF data according the date mentioned in the filename
`exiftool -r -P "-FileName>AllDates" /home/thomas/pictures/IMG-20200307-WA0001.jpg`
Which results in the following EXIF data
```
thomas@ubuntu:~/elodie$ exiftool -time:all -G0:1 -s /home/thomas/pictures/IMG-20200307-WA0001.jpg
[File:System]   FileModifyDate                  : 2020:04:08 11:09:23+00:00
[File:System]   FileAccessDate                  : 2020:04:08 12:06:58+00:00
[File:System]   FileInodeChangeDate             : 2020:04:08 12:41:20+00:00
[EXIF:IFD0]     ModifyDate                      : 2020:03:07 00:01:00
[EXIF:ExifIFD]  DateTimeOriginal                : 2020:03:07 00:01:00
[EXIF:ExifIFD]  CreateDate                      : 2020:03:07 00:01:00

```
After running this command elodie should be able to correctly rename the Whatsapp image and put it in the correct folder structure.

But my question is more related to the moving of a file to a fallback folder.
In the docs it it mentioned that files not having %location can be moved to "Beats me"
```
[Directory]
month=%m
year=%Y
location=%city
full_path=%month/%year/%album|%location|%"Beats me"
```

But can the same be done for files not having the DateTimeOriginal  EXIF tag?
Then I can use the command above to fix the EXIF data an run elodie again over the fixed files.

Sorry for the wall of text but this way I can sketch my whole story

Kr,
Thomas.

**Comment by jmathai** [comment]
Hi @thomaspriv  - The order in which a file's date is determined is [documented here](https://github.com/jmathai/elodie#exif-and-xmp-tags). If there are issued related to this please open a separate issue specifically to look into it.

Because of the way a file's date is determined there's never a case where it's *not set*. Worst case we look at the file system's date modified or create. So what you're asking for is not currently supported. Reopen if your this is important and you'd like to keep it open as a feature request.

Full disclosure - it's unlikely that this will be easily supported since we already have a fallback that assumes there's always a date/time we can extract. To support this we would likely need to have a configuration value to change this behavior which adds non-trivial complexity to the code --- so it would need to create disproportional value to warrant :)

Thanks for the detailed description.
