### ISSUE TITLE
What's the point of differentiating --source and --file ?

### ISSUE THREAD

**Issue by Kraymer** [jmathai/elodie#60]
ie why not provide a single ``--source`` option and handle the "the source is a file" edge case in the code.

**Comment by noonat** [comment]
I have a similar problem, where I'm trying to pipe an Automator folder action into an Elodie import. Automator gives me a list of filenames, so I'm forced to do an import file by file. I don't want to import the directory because I have other actions running that may cause race conditions if Automator starts two simultaneous workflows.

Seems like it would be easier to just make the syntax the same as update. That is, something like:

    elodie.py import --destination=<d> [--album-from-folder] INPUT ...

For each input, if it's a directory it would grab all the files from that directory, and if its a file it would just apply to that file.

**Comment by jmathai** [comment]
I like @noonat's suggestion and think I prefer it over having `--source` and `--file` at all. We can leave them in for deprecated support but a list of arguments makes the most sense for input. Let me look at the PR.
