### ISSUE TITLE
Support ARW format

### ISSUE THREAD

**Issue by Ramblurr** [jmathai/elodie#99]
I'd like to make a pull request to support Sony's ARW format. I've added it to the list of valid extensions, and it seems to be working fine, however some tests are needed.

Could you please add documentation to the Readme on how to run the tests? 

So far I'm stuck after
```
pip install -r elodie/tests/requirements.txt
# .... then?
```

**Comment by jmathai** [comment]
We need to add docs for this. To run the tests you can do the following from the root of the repository.

```
cd elodie
nosetests -w tests/
```

You can look at this commit which added tests for `RW2` files.
https://github.com/jmathai/elodie/commit/1c0372141f57355564aab38b353bcdc68a55301c

In order to not add large files to the repository the test will fetch the file from an S3 bucket. To simulate this you can place the file at `elodie/tests/files/photo.arw` and use `photo_file = helper.get_file('photo.arw')` in the test.

You will probably need to set the assertion for the date based on the photo you're using for testing. Once ready you can submit the PR and either provide a link to the `arw` file or email it to me jaisen(at)githubusername(dot)com

Let me know if that makes sense.

**Comment by jmathai** [comment]
Feel free to add a `elodie/tests/Readme.md` which outlines the steps to test.

**Comment by jmathai** [comment]
I added support for ARW file and associated tests.
